
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.


def main(limit: int):
    previous_number = 1
    next_number = 1
    sum = 0
    while next_number < limit:
        current_number = next_number
        if current_number % 2 == 0:
            sum += current_number
        next_number = current_number + previous_number
        previous_number = current_number

    print(sum)


if __name__ == '__main__':
    main(4_000_000)
